language: node_js
node_js:
- stable
after_success:
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: KRuIjRMQxVYIUzYL9tDtiaj9+crwrmT5E3Xi9q9RSfZIK0JhqmwAY1zGVJ7x9aSs6MOw8rGIBAP6TA2BCHmnH88fsDQ27/YiX9kOvHtSfxoG3EjapjUfi4IS3CIz5S8nXm+QtwVmhnWi5iYhDrksupefoo+t2KTJpvcEf87lXRI84vM739Yjk3y4TWA2K2BRjuX2wLAYB+58KPQfqSt1hprvhkJuE8MMSezFLysU5X9eAOg8EQ+ooNj6Od8+VQEa6X9GCm6V4G6qjXKJdWSsEp5E1RGaVLCz1j0WD2H3Fnsh4mEmzuhaUXMcJeE7MvVXmGbTPoug0fJyDtqHFCiI0F3VaqRRTVq7TriC2GCns3504PRHYs/0QrAcRNUV0+rRrluQY/itQ1zgtTdChlYrqZoggpKGshl4IAsb5np36JXAUZ+HsmUhQsP1ocCZOUqjZamklDkeqZzHzWxYVNHxvC61ZI5xCkXOqMSsj87nWKtr3u2vAFVmZMk++kcEdf3UrGKZO7J+5hnXp0MpYRfyexYlzKJ5bLc4iqFqIP2yBd+8iydC41yqx2u9uY2WDXUfncZTA/FtU+HI3LIqNTSE/6FSIq63dsK6240jCAdHdtO7G8nZuRWJyc2pS4b9ASvqHkpZBmCAF76H7z6Nh/flnoBNhi8v9qXDPaVx4A/Ck2o=
  on:
    tags: true
    repo: up9cloud/docsify-mindmap
    branch: master
  skip_cleanup: true
